backend:
  name: git-gateway
  branch: main
  accept_roles:
    - admin
    - editor
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: '{{slug}}.html'
      - &ref_0
        label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
  - name: featured_icons
    label: Featured icons
    folder: cms/featured-icons
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - hint: ''
        name: f_icon
        label: icon
        widget: object
        required: false
        fields:
          - hint: ''
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: string
            required: false
      - label: Tags
        widget: hidden
        name: tags
        default: featured-icons
      - label: Layout
        widget: hidden
        name: layout
        default: '[featured-icons].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - name: big_numbers
    label: Big numbers
    folder: cms/big-numbers
    create: true
    identifier_field: name
    extension: md
    slug: '{{slug}}'
    fields:
      - hint: ''
        name: title
        label: Name
        widget: string
        required: true
      - hint: ''
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ''
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ''
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - hint: ''
        name: f_description
        label: description
        widget: text
        required: false
      - hint: order at which the big numbers appears
        name: f_order
        label: order
        widget: number
        required: false
      - label: Tags
        widget: hidden
        name: tags
        default: big-numbers
      - label: Layout
        widget: hidden
        name: layout
        default: '[big-numbers].html'
      - label: Publish Date
        name: date
        widget: datetime
      - *ref_0
  - label: Theme Settings
    name: settings
    identifier_field: title
    extension: json
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: General
        name: site
        file: cms/_data/settings/site.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: General
          - hint: Full domain url (needed for a correct sitemap file)
            name: domain
            label: Domain
            widget: string
            required: false
          - name: favicon
            label: Favicon
            widget: image
            allow_multiple: false
            required: false
          - name: apple_touch_icon
            label: Apple Touch Icon
            widget: image
            allow_multiple: false
            required: false
          - name: header_additional_content
            label: Additional Content Header
            hint: Content here will be placed before </head> tag
            widget: text
            required: false
          - name: footer_additional_content
            label: Additional Content Footer
            hint: Content here will be placed before </body> tag
            widget: text
            required: false
          - name: images_optimization
            label: Images Optimization
            widget: object
            collapsed: false
            fields:
              - label: Image Formats
                name: formats
                widget: select
                multiple: true
                options:
                  - label: Avif
                    value: avif
                  - label: Webp
                    value: webp
              - label: Image Dimensions
                name: dimensions
                widget: select
                multiple: true
                options:
                  - label: '500'
                    value: 500
                  - label: '800'
                    value: 800
                  - label: '1080'
                    value: 1080
                  - label: '1600'
                    value: 1600
                  - label: '2000'
                    value: 2000
                  - label: '2600'
                    value: 2600
      - label: Colors
        name: colors
        file: cms/_data/colors.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Colors
      - label: Texts
        name: texts
        file: cms/_data/texts.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Texts
          - hint: 'Original text: Projects, key: -37ac8366'
            label: Text
            name: '-37ac8366'
            widget: string
          - hint: 'Original text: Clients, key: -697be218'
            label: Text
            name: '-697be218'
            widget: string
          - hint: 'Original text: Contact, key: -64104400'
            label: Text
            name: '-64104400'
            widget: string
          - hint: 'Original text: Disclaimer, key: -6f68ae45'
            label: Text
            name: '-6f68ae45'
            widget: string
          - hint: 'Original text: Privacy Policy, key: -3fbde6f6'
            label: Text
            name: '-3fbde6f6'
            widget: string
          - hint: >-
              Original text: Empowering businesses with cutting edge , key:
              3a69bd0
            label: Text
            name: 3a69bd0
            widget: string
          - hint: 'Original text: Web3, key: 29137f'
            label: Text
            name: 29137f
            widget: string
          - hint: 'Original text:  solutions, key: 4dea85fa'
            label: Text
            name: 4dea85fa
            widget: string
          - hint: 'Original text: Talk to us, key: -7d8e69f1'
            label: Text
            name: '-7d8e69f1'
            widget: string
          - hint: 'Original text: Services, key: 560f747e'
            label: Text
            name: 560f747e
            widget: string
          - hint: 'Original text: No items found., key: 3d503d2b'
            label: Text
            name: 3d503d2b
            widget: string
          - hint: 'Original text: Our services, key: fcf0ad2'
            label: Text
            name: fcf0ad2
            widget: string
          - hint: >-
              Original text: Leveraging state-of-the-art technology to
              revolutionize digital spaces., key: 18759d4e
            label: Text
            name: 18759d4e
            widget: string
          - hint: 'Original text: UX/UI, key: 4d68980'
            label: Text
            name: 4d68980
            widget: string
          - hint: 'Original text: Design, key: 79ceadde'
            label: Text
            name: 79ceadde
            widget: string
          - hint: >-
              Original text: A focus on smooth UX/UI and expertly crafted user
              flow your community will love., key: 47340c4c
            label: Text
            name: 47340c4c
            widget: string
          - hint: 'Original text: Development, key: 5603451b'
            label: Text
            name: 5603451b
            widget: string
          - hint: >-
              Original text: Build and maintain complex systems tailored to our
              client's needs, focusing on security and gas efficiency., key:
              -7824c847
            label: Text
            name: '-7824c847'
            widget: text
          - hint: 'Original text: DeFi, key: 206d44'
            label: Text
            name: 206d44
            widget: string
          - hint: 'Original text: Consulting, key: 6ce1e096'
            label: Text
            name: 6ce1e096
            widget: string
          - hint: >-
              Original text: Extensive experience in designing and planning
              complex systems to support you in launching quality products
              tailored to your needs., key: 5ca55115
            label: Text
            name: 5ca55115
            widget: text
          - hint: 'Original text: Server, key: -6c98e49d'
            label: Text
            name: '-6c98e49d'
            widget: string
          - hint: 'Original text: Managment, key: 5b39783e'
            label: Text
            name: 5b39783e
            widget: string
          - hint: >-
              Original text: We specialize in managing servers for you,
              providing reliable and secure hosting solutions., key: -37266504
            label: Text
            name: '-37266504'
            widget: text
      - label: Links
        name: links
        file: cms/_data/links.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Links
          - hint: 'Original link: #, key: 23'
            label: Link
            name: '23'
            widget: string
          - hint: 'Original link: #services, key: -686fc27f'
            label: Link
            name: '-686fc27f'
            widget: string
      - label: Images
        name: images
        file: cms/_data/images.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Images
          - label: Image
            name: 3db6a09d
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: '-58527a2e'
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 30d6d84d
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
publish_mode: editorial_workflow
